config/routes.rb
Rails.application.routes.draw do
  root "movies#index"

  get   "/movie/new"      => "movies#new",    as: :new_movie
  post  "/movie"          => "movies#create", as: :create_movie
  get   "/movie/edit/:id" => "movies#edit",   as: :edit_movie
  patch "/movie/:id"      => "movies#update", as: :update_movie
  get   "/movie/:id"      => "movies#show",   as: :show_movie
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
require "movies/creator"
require "movies/presenter"
require "movies/updater"

class MoviesController < ApplicationController
  def index
    @movies = Movie.all.map {|movie| Movies::Presenter.new(movie)}
  end

  def new
    @movie = Movie.new
  end

  def create
    creation = Movies::Creator.execute(movie_params)

    if creation.successful?
      redirect_to root_path, notice: "Successfully created movie #{creation.movie.title}."
    else
      @movie = creation.movie
      flash.now[:alert] = creation.messages
      render :new
    end
  end

  def edit
    @movie = Movie.find(movie_id)
  end

  def update
    update = Movies::Updater.execute(movie_id, movie_params)

    if update.successful?
      redirect_to root_path, notice: "Successfully updated movie #{update.movie.title}."
    else
      @movie = update.movie
      flash.now[:alert] = update.messages
      render :edit
    end
  end

  def show
    @movie = Movies::Presenter.new(Movie.find(movie_id))
  end

  private

  def movie_params
    params.require(:movie).permit(:id, :title, :release_date, :description)
  end

  def movie_id
    params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailTrack</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <h1>Movies</h1>

  <% if flash.any? %>
    <ul class="flashes">
      <% flash.alert.try(:each) do |alert| %>
        <li class="alert"><%= alert %></li>
      <% end %>

      <% if flash.notice %>
        <li class="notice"><%= flash.notice %></li>
      <% end %>
    </ul>
  <% end %>

  <%= yield %>
</body>
</html>

app/views/movies/edit.html.erb
<h2>Edit Movie</h2>

<%= form_for(@movie, url: update_movie_path) do |form| %>
  <%= form.label(:title) %>
  <%= form.text_field(:title) %>

  <%= form.label(:release_date) %>
  <%= form.date_field(:release_date) %>

  <%= form.label(:description) %>
  <%= form.text_field(:description) %>

  <%= form.submit %>
<% end %>

app/views/movies/index.html.erb
<nav>
  <%= link_to "Add New Movie", new_movie_path %>
</nav>

<% if @movies.any? %>
  <ul>
  <% @movies.each do |movie| %>
    <li>
      <header>
        <%= link_to(movie.title, show_movie_path(movie.id)) %> <time><%= movie.release_date %></time>
      </header>
      <nav>
        <%= link_to("Edit Movie", edit_movie_path(movie.id), class: "edit") %>
      </nav>
    </li>
  <% end %>
  </ul>
<% else %>
  <p>No movies have been added yet.</p>
<% end %>

app/views/movies/new.html.erb
<h2>Add New Movie</h2>

<%= form_for(@movie, url: create_movie_path) do |form| %>
  <%= form.label(:title) %>
  <%= form.text_field(:title) %>

  <%= form.label(:release_date) %>
  <%= form.date_field(:release_date) %>

  <%= form.label(:description) %>
  <%= form.text_field(:description) %>

  <%= form.submit %>
<% end %>

app/views/movies/show.html.erb
<h2><%= @movie.title %></h2>
<h3>Release Date: <time><%= @movie.release_date %></time></h3>

<p><%= @movie.description %><p>